packages:
- .

extra-deps:
- cabal-macosx-0.2.4.1
- reactive-banana-1.2.1.0
- git: https://github.com/gloaming/reactive-banana
  commit: e8e13db3f7901c07d02d7f0e609a65e951e6ae97
  subdirs:
  - reactive-banana-wx
- git: https://github.com/gloaming/wxHaskell
  commit: dd893e8e4456f7bac9260774823050ff4b136119
  subdirs:
  - wx
  - wxc
  - wxcore
  - wxdirect

resolver: lts-13.29

nix:
  packages: [ mesa.dev wxGTK30 xorg.libX11.dev ]
